#服务器配置
server:
  port: 8989
  servlet:
    context-path: /
spring:
  #项目配置
  application:
    name: pstoolkit
  #Redis配置
  redis:
    # 基本连接配置
    host: your_redis_host
    port: 6379
    password: your_redis_password
    database: 0
    timeout: 2000ms
    # Lettuce连接池配置
    lettuce:
      pool:
        max-active: 20
        max-wait: -1ms
        max-idle: 10
        min-idle: 0
      # 关闭超时时间
      shutdown-timeout: 100ms